alias be='bundle exec'
alias l='ls'
alias less='less -R'

# Git aliases

alias gg='git grep'
alias gst='git status'
alias glg='git lg'
alias gbr='git branch'
alias 'ga.'='git add -A .'
alias gadd='git add'
alias gck='git checkout'
alias gco='git commit'
alias grebase='git rebase'
alias gdiff='git diff'
alias gfetch='git fetch'
alias gfix='git fix'
alias gmerge='git merge'
alias gpull='git pull'
alias gpush='git push'
alias gremote='git remote'
alias greset='git reset'
alias grework='git rework'
alias gshow='git show'
alias gstash='git stash'
